version: '3'

services:
  mysql:
      image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD: "root"
        MYSQL_DATABASE: "docker"
      volumes:   
        - C:\Docker\banco:/var/lib/mysql
      ports:
        - "3308:3306"
  java:
    image: sts:1.0
    environment:
      spring_jpa_database: "MYSQL"
      spring_datasource_url: "jdbc:mysql://mysql:3306/docker?createDatabaseIfNotExist=true&useSSL=false"
      spring_datasource_username: "root"
      spring_datasource_password: "root"
      spring_jpa_show-sql: "true"
    ports:
    - "8083:8080"
    depends_on:
      - mysql